server.port=8081    

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tarefas
spring.datasource.username=tarefas
spring.datasource.password=123321
spring.datasource.driver-class-name=org.postgresql.Driver

# Cria/atualiza tabelas automaticamente enquanto está em dev
spring.jpa.hibernate.ddl-auto=update
jwt.secret=2s8P3p9DkvuvUYfHfbxP1t4MCtjVApDFM7nKqzNhRULxPXZ9gvopxS5xvO2VoDZFcM7Ec2gaOkTgTbdJkRI5dQ==
jwt.expiration=86400000