server.port=8081    

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tarefas
spring.datasource.username=tarefas
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver

# Cria/atualiza tabelas automaticamente enquanto está em dev
spring.jpa.hibernate.ddl-auto=update